spring:
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
      timeout: 0
  devtools:
      restart:
        enabled: true
        exclude: static/**,templates/**
      livereload:
        enabled: true
      remote:
        debug:
          enabled: true
logging:
  level: debug