spring:
    application:
        name: learning-spring
server:
  port: 8080
logging:
   file: /logs/stn.log
   level:
     root: info

# 设置spring boot 启动的banner
banner:
  location: classpath:banner-girl.txt